// Made written by ali hasan
import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.feed': 'Feed',
    'nav.profile': 'Profile',
    'nav.connections': 'Connections',
    'nav.messages': 'Messages',
    'nav.jobs': 'Jobs',
    'nav.events': 'Events',
    'nav.groups': 'Groups',
    'nav.search': 'Search',
    'nav.admin': 'Admin',
    'nav.login': 'Sign In',
    'nav.register': 'Get Started',
    'nav.logout': 'Logout',
    'nav.companies': 'Companies',
    'nav.users': 'Users',
    
    // Landing Page
    'landing.title': 'Connect. Collaborate. Grow.',
    'landing.titleHighlight': 'Grow.',
    'landing.subtitle': 'The premier B2B social network for businesses to connect, share opportunities, and build lasting partnerships.',
    'landing.cta.getStarted': 'Get Started Free',
    'landing.cta.signIn': 'Sign In',
    'landing.stats.companies': '10K+',
    'landing.stats.companiesLabel': 'Companies',
    'landing.stats.connections': '50K+',
    'landing.stats.connectionsLabel': 'Connections',
    'landing.stats.events': '5K+',
    'landing.stats.eventsLabel': 'Events',
    'landing.stats.industries': '100+',
    'landing.stats.industriesLabel': 'Industries',
    'landing.features.title': 'Everything You Need to Succeed',
    'landing.features.subtitle': 'Powerful tools designed for modern business networking',
    'landing.features.profiles.title': 'Company Profiles',
    'landing.features.profiles.description': 'Create detailed company profiles showcasing your business, services, and expertise.',
    'landing.features.connections.title': 'Business Connections',
    'landing.features.connections.description': 'Connect with other businesses, form partnerships, and expand your network.',
    'landing.features.jobs.title': 'Job Postings',
    'landing.features.jobs.description': 'Post and find job opportunities within the B2B community.',
    'landing.features.events.title': 'Events',
    'landing.features.events.description': 'Discover and host industry events, webinars, and networking sessions.',
    'landing.features.groups.title': 'Groups',
    'landing.features.groups.description': 'Join industry-specific groups to discuss trends and share insights.',
    'landing.features.reviews.title': 'Reviews & Ratings',
    'landing.features.reviews.description': 'Build trust with verified reviews and ratings from business partners.',
    'landing.testimonials.title': 'Trusted by Businesses Worldwide',
    'landing.testimonials.testimonial1.quote': "B2BNet helped us find amazing partners we never would have discovered otherwise.",
    'landing.testimonials.testimonial1.author': "Sarah Chen",
    'landing.testimonials.testimonial1.role': "CEO, TechVentures Inc.",
    'landing.testimonials.testimonial2.quote': "The networking opportunities on this platform have transformed our business.",
    'landing.testimonials.testimonial2.author': "Michael Rodriguez",
    'landing.testimonials.testimonial2.role': "Director, Global Solutions Ltd.",
    'landing.testimonials.testimonial3.quote': "We've secured multiple contracts through connections made on B2BNet.",
    'landing.testimonials.testimonial3.author': "Emily Watson",
    'landing.testimonials.testimonial3.role': "VP Sales, InnovateCorp",
    'landing.cta.title': 'Ready to Grow Your Business Network?',
    'landing.cta.subtitle': 'Join thousands of companies already connecting on B2BNet',
    'landing.cta.createAccount': 'Create Your Account',
    'footer.tagline': 'Connecting businesses, building partnerships.',
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.about': 'About',
    'footer.helpCenter': 'Help Center',
    'footer.contact': 'Contact',
    'footer.documentation': 'Documentation',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.security': 'Security',
    'footer.copyright': '© 2026 B2BNet. All rights reserved. by',
    
    // Features Page
    'features.title': 'Features',
    'features.subtitle': 'Everything you need to succeed on our platform',
    'features.analytics': 'Advanced Analytics',
    'features.analyticsDesc': 'Gain insights with detailed analytics and reporting tools to track your performance.',
    'features.security': 'Enterprise Security',
    'features.securityDesc': 'Bank-level security with end-to-end encryption to keep your data safe.',
    'features.global': 'Global Reach',
    'features.globalDesc': 'Connect with businesses worldwide and expand your market presence.',

    // Pricing Page
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Choose the plan that fits your business needs',
    'pricing.free': 'Free',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.perMonth': '/month',
    'pricing.basicProfile': 'Basic Company Profile',
    'pricing.limitedConnections': 'Limited Connections (50)',
    'pricing.basicSearch': 'Basic Search',
    'pricing.getStarted': 'Get Started',
    'pricing.enhancedProfile': 'Enhanced Company Profile',
    'pricing.unlimitedConnections': 'Unlimited Connections',
    'pricing.advancedAnalytics': 'Advanced Analytics',
    'pricing.prioritySupport': 'Priority Support',
    'pricing.startTrial': 'Start Free Trial',
    'pricing.mostPopular': 'Most Popular',
    'pricing.custom': 'Custom',
    'pricing.customIntegrations': 'Custom Integrations',
    'pricing.dedicatedSupport': 'Dedicated Support',
    'pricing.sla': 'SLA Guarantee',
    'pricing.apiAccess': 'API Access',
    'pricing.contactSales': 'Contact Sales',

    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Building the future of business networking',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'To empower businesses worldwide by creating meaningful connections and opportunities for growth.',
    'about.vision': 'Our Vision',
    'about.visionDesc': 'A global network where every business can thrive, collaborate, and succeed together.',
    'about.values': 'Our Values',
    'about.trust': 'Trust',
    'about.trustDesc': 'We build lasting relationships through transparency and integrity.',
    'about.innovation': 'Innovation',
    'about.innovationDesc': 'We continuously evolve to meet the changing needs of modern businesses.',
    'about.community': 'Community',
    'about.communityDesc': 'We believe in the power of community and collaboration.',
    'about.excellence': 'Excellence',
    'about.excellenceDesc': 'We strive for excellence in everything we do.',
    'about.team': 'Our Team',
    'about.teamDesc': 'Our diverse team of experts is dedicated to making B2B networking accessible and effective for businesses of all sizes.',

    // Help Center Page
    'help.title': 'Help Center',
    'help.subtitle': 'Find answers to common questions',
    'help.gettingStarted': 'Getting Started',
    'help.gettingStartedDesc': 'Learn how to create your account, set up your profile, and start networking.',
    'help.faq': 'Frequently Asked Questions',
    'help.faq1.q': 'How do I create a company profile?',
    'help.faq1.a': 'After registering, go to your dashboard and click "Complete Profile". Fill in your company details and save.',
    'help.faq2.q': 'How can I connect with other companies?',
    'help.faq2.a': 'Use the Connections page to search for companies and send connection requests. Once accepted, you can start collaborating.',
    'help.faq3.q': 'How do I post a job?',
    'help.faq3.a': 'Navigate to the Jobs page and click "Post a Job". Fill in the details and publish to reach thousands of businesses.',
    'help.faq4.q': 'Can I host events on the platform?',
    'help.faq4.a': 'Yes! Go to the Events page and click "Create Event". You can host both virtual and in-person events.',
    'help.faq5.q': 'How do I report inappropriate content?',
    'help.faq5.a': 'Click the "Report" button on any post or profile. Our moderation team will review it within 24 hours.',
    'help.needMoreHelp': 'Need More Help?',
    'help.needMoreHelpDesc': 'Our support team is available 24/7 to assist you with any questions or issues.',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.addressValue': '123 Business Ave, Suite 100\nSan Francisco, CA 94107\nUnited States',
    'contact.yourName': 'Your Name',
    'contact.yourEmail': 'Your Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.sendMessage': 'Send Message',
    'contact.messageSent': 'Your message has been sent! We\'ll get back to you soon.',

    // Documentation Page
    'docs.title': 'Documentation',
    'docs.subtitle': 'Comprehensive guides and API references',
    'docs.gettingStarted': 'Getting Started',
    'docs.gettingStartedDesc': 'Learn the basics of using our platform and API.',
    'docs.apiReference': 'API Reference',
    'docs.apiReferenceDesc': 'Complete API documentation with examples and endpoints.',
    'docs.guides': 'Guides & Tutorials',
    'docs.guidesDesc': 'Step-by-step tutorials to help you get the most out of our platform.',
    'docs.support': 'Support',
    'docs.supportDesc': 'Additional resources and contact information for technical support.',

    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'How we protect and use your data',
    'privacy.collection': 'Information We Collect',
    'privacy.collectionDesc': 'We collect information you provide directly, such as your company details, profile information, and communications. We also collect usage data to improve our services.',
    'privacy.usage': 'How We Use Your Information',
    'privacy.usageDesc': 'We use your information to provide and improve our services, facilitate connections, send updates, and communicate with you. We never sell your personal data.',
    'privacy.sharing': 'Information Sharing',
    'privacy.sharingDesc': 'We share your information only with your consent or as necessary to provide our services. This includes connecting you with other businesses on the platform.',
    'privacy.security': 'Data Security',
    'privacy.securityDesc': 'We implement industry-standard security measures to protect your data, including encryption, access controls, and regular security audits.',
    'privacy.rights': 'Your Rights',
    'privacy.rightsDesc': 'You have the right to access, correct, or delete your personal data. You can also opt out of certain data processing activities.',

    // Terms Page
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'Rules and guidelines for using our platform',
    'terms.acceptance': 'Acceptance of Terms',
    'terms.acceptanceDesc': 'By accessing or using B2BNet, you agree to be bound by these Terms of Service. If you do not agree, you may not use the service.',
    'terms.use': 'Use of Service',
    'terms.useDesc': 'Our platform is for legitimate business purposes only. You agree to use the service in accordance with all applicable laws and regulations.',
    'terms.accounts': 'Accounts',
    'terms.accountsDesc': 'You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.',
    'terms.content': 'User Content',
    'terms.contentDesc': 'You retain ownership of content you post, but grant us a license to use it for providing and improving our services. Content must not violate intellectual property rights.',
    'terms.termination': 'Termination',
    'terms.terminationDesc': 'We reserve the right to suspend or terminate accounts that violate these terms or engage in harmful activities.',

    // Security Page
    'security.title': 'Security',
    'security.subtitle': 'How we protect your business data',
    'security.encryption': 'End-to-End Encryption',
    'security.encryptionDesc': 'All data transmitted between your browser and our servers is encrypted using TLS 1.3. We also encrypt sensitive data at rest.',
    'security.authentication': 'Secure Authentication',
    'security.authenticationDesc': 'We support multi-factor authentication and use secure password hashing algorithms to protect your account.',
    'security.monitoring': '24/7 Monitoring',
    'security.monitoringDesc': 'Our security team monitors systems around the clock to detect and respond to potential threats.',
    'security.compliance': 'Compliance',
    'security.complianceDesc': 'We comply with industry standards and regulations including GDPR, CCPA, and SOC 2 Type II.',
    'security.reporting': 'Vulnerability Reporting',
    'security.reportingDesc': 'We encourage responsible disclosure of security vulnerabilities. Contact our security team to report any issues.',

    // Auth Pages
    'auth.welcomeBack': 'Welcome back',
    'auth.signInSubtitle': 'Sign in to your B2B Network account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.emailPlaceholder': 'company@example.com',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.signIn': 'Sign In',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.or': 'or',
    'auth.createAccount': 'Create New Account',
    'auth.noAccount': "Don't have an account? ",
    'auth.registerHere': 'Register here',
    'auth.joinBusinesses': 'Join thousands of businesses on our platform',
    'auth.registrationFailed': 'Registration failed. Email may already exist.',
    'auth.companyInfo': 'Company Info',
    'auth.accountDetails': 'Account Details',
    'auth.companyName': 'Company Name',
    'auth.companyPlaceholder': 'Your Company Inc.',
    'auth.industry': 'Industry',
    'auth.selectIndustry': 'Select industry',
    'auth.description': 'Description',
    'auth.descriptionPlaceholder': 'Brief description of your company',
    'auth.website': 'Website',
    'auth.websitePlaceholder': 'https://yourcompany.com',
    'auth.location': 'Location',
    'auth.locationPlaceholder': 'City, Country',
    'auth.companySize': 'Company Size',
    'auth.selectSize': 'Select size',
    'auth.yourName': 'Your Name',
    'auth.namePlaceholder': 'John Doe',
    'auth.logoUrl': 'Logo URL (optional)',
    'auth.logoPlaceholder': 'https://example.com/logo.png',
    'auth.continueAccount': 'Continue to Account Details',
    'auth.back': 'Back',
    'auth.signInInstead': 'Sign In Instead',
    'auth.haveAccount': 'Already have an account? ',
    'auth.growBusiness': 'Grow your business network',
    'auth.connectPartners': 'Connect with partners, clients, and industry leaders',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats.connections': 'Connections',
    'dashboard.stats.posts': 'Recent Posts',
    'dashboard.stats.jobs': 'Active Jobs',
    'dashboard.stats.events': 'Upcoming Events',
    'dashboard.recentPosts': 'Recent Posts',
    'dashboard.latestJobs': 'Latest Jobs',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.viewAllPosts': 'View All Posts',
    'dashboard.viewAllJobs': 'View All Jobs',
    'dashboard.viewAllEvents': 'View All Events',
    
    // Feed
    'feed.createPost': 'Create a Post',
    'feed.postPlaceholder': "What's happening in your business?",
    'feed.postButton': 'Post',
    'feed.companyId': 'Company ID',
    
    // Profile
    'profile.verified': 'Verified',
    'profile.industry': 'Industry',
    'profile.location': 'Location',
    'profile.size': 'Size',
    'profile.website': 'Website',
    'profile.description': 'Description',
    'profile.notSpecified': 'Not specified',
    'profile.noDescription': 'No description provided',
    'profile.badges': 'Badges',
    'profile.connections': 'Connections',
    'profile.noConnections': 'No connections yet',
    'profile.connectionId': 'Connection ID',
    'profile.status': 'Status',
    'profile.reviews': 'Reviews',
    'profile.noReviews': 'No reviews yet',
    'profile.reviewer': 'Reviewer',
    'profile.connected': 'You are connected',
    'profile.requestSent': 'Connection request sent - awaiting response',
    'profile.sendRequest': 'Send Connection Request',
    
    // Connections
    'connections.sendRequest': 'Send Connection Request',
    'connections.selectCompany': 'Select a company',
    'connections.sendRequestButton': 'Send Request',
    'connections.pendingRequests': 'Pending Requests',
    'connections.from': 'From',
    'connections.accept': 'Accept',
    'connections.reject': 'Reject',
    'connections.yourConnections': 'Your Connections',
    'connections.noConnections': 'No connections yet. Send requests to other companies to build your network!',
    'connections.connectedWith': 'Connected with',
    'connections.connectedOn': 'Connected on',
    'connections.remove': 'Remove',
    'connections.requestSent': 'Connection request sent!',
    'connections.requestFailed': 'Failed to send request. It may already exist.',
    'connections.removeConfirm': 'Are you sure you want to remove this connection?',
    
    // Messages
    'messages.conversations': 'Conversations',
    'messages.chatWith': 'Chat with',
    'messages.typeMessage': 'Type a message...',
    'messages.send': 'Send',
    'messages.selectCompany': 'Select a company to start chatting',
    
    // Jobs
    'jobs.postJob': 'Post a Job',
    'jobs.createPosting': 'Create Job Posting',
    'jobs.title': 'Title',
    'jobs.description': 'Description',
    'jobs.requirements': 'Requirements',
    'jobs.location': 'Location',
    'jobs.type': 'Job Type',
    'jobs.salary': 'Salary Range (optional)',
    'jobs.fullTime': 'Full-time',
    'jobs.partTime': 'Part-time',
    'jobs.contract': 'Contract',
    'jobs.freelance': 'Freelance',
    'jobs.deleteConfirm': 'Are you sure you want to delete this job?',
    
    // Events
    'events.createEvent': 'Create Event',
    'events.title': 'Title',
    'events.description': 'Description',
    'events.datetime': 'Date & Time',
    'events.location': 'Location',
    'events.type': 'Event Type',
    'events.networking': 'Networking',
    'events.conference': 'Conference',
    'events.webinar': 'Webinar',
    'events.workshop': 'Workshop',
    'events.meetup': 'Meetup',
    'events.virtual': 'Virtual Event',
    'events.meetingLink': 'Meeting Link',
    'events.deleteConfirm': 'Are you sure you want to delete this event?',
    
    // Groups
    'groups.createGroup': 'Create Group',
    'groups.name': 'Group Name',
    'groups.description': 'Description',
    'groups.industry': 'Industry',
    'groups.private': 'Private Group',
    'groups.public': 'Public',
    'groups.deleteConfirm': 'Are you sure you want to delete this group?',
    
    // Search
    'search.placeholder': 'Search companies, posts, jobs, events, groups...',
    'search.all': 'All',
    'search.noResults': 'No results found',
    
    // Admin
    'admin.stats': 'Statistics',
    'admin.totalCompanies': 'Total Companies',
    'admin.totalUsers': 'Total Users',
    'admin.totalPosts': 'Total Posts',
    'admin.totalConnections': 'Total Connections',
    'admin.totalJobs': 'Total Jobs',
    'admin.totalEvents': 'Total Events',
    'admin.totalGroups': 'Total Groups',
    'admin.manageCompanies': 'Manage Companies',
    'admin.managePosts': 'Manage Posts',
    'admin.manageUsers': 'Manage Users',
    'admin.manageEvents': 'Manage Events',
    'admin.manageGroups': 'Manage Groups',
    'admin.manageJobs': 'Manage Jobs',
    'admin.manageMessages': 'Manage Messages',
    'admin.company': 'Company',
    'admin.role': 'Role',
    'admin.userRole': 'User',
    'admin.adminRole': 'Admin',
    'admin.deleteCompanyConfirm': 'Are you sure you want to delete this company?',
    'admin.deletePostConfirm': 'Are you sure you want to delete this post?',
    'admin.deleteEventConfirm': 'Are you sure you want to delete this event?',
    'admin.deleteGroupConfirm': 'Are you sure you want to delete this group?',
    'admin.deleteJobConfirm': 'Are you sure you want to delete this job?',
    'admin.banUser': 'Ban User',
    'admin.unbanUser': 'Unban User',
    'admin.banCompany': 'Ban Company',
    'admin.unbanCompany': 'Unban Company',
    'admin.banConfirm': 'Are you sure you want to ban this {type}? This will prevent them from accessing the platform.',
    'admin.unbanConfirm': 'Are you sure you want to unban this {type}?',
    'admin.edit': 'Edit',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.search': 'Search',
    'admin.filter': 'Filter',
    'admin.bulkActions': 'Bulk Actions',
    'admin.selectAll': 'Select All',
    'admin.deleteSelected': 'Delete Selected',
    'admin.banSelected': 'Ban Selected',
    'admin.settings': 'System Settings',
    'admin.siteSettings': 'Site Settings',
    'admin.maintenanceMode': 'Maintenance Mode',
    'admin.enableMaintenance': 'Enable Maintenance Mode',
    'admin.disableMaintenance': 'Disable Maintenance Mode',
    'admin.maintenanceWarning': 'Site is currently in maintenance mode. Only admins can access.',
    'admin.registrationOpen': 'Registration Open',
    'admin.toggleRegistration': 'Toggle Registration',
    'admin.registrationOpenDesc': 'Allow new users to register',
    'admin.registrationClosed': 'Registration is closed',
    'admin.analytics': 'Analytics',
    'admin.systemLogs': 'System Logs',
    'admin.viewLogs': 'View Logs',
    'admin.clearLogs': 'Clear Logs',
    'admin.exportData': 'Export Data',
    'admin.importData': 'Import Data',
    'admin.backup': 'Backup',
    'admin.restore': 'Restore',
    'admin.createBackup': 'Create Backup',
    'admin.restoreBackup': 'Restore from Backup',
    'admin.noItems': 'No items found',
    'admin.addNew': 'Add New',
    'admin.view': 'View',
    'admin.createdAt': 'Created',
    'admin.updatedAt': 'Updated',
    'admin.status': 'Status',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.banned': 'Banned',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.all': 'All',
    'admin.confirmAction': 'Confirm Action',
    'admin.actionSuccess': 'Action completed successfully',
    'admin.actionFailed': 'Action failed. Please try again.',
    'admin.loading': 'Loading...',
    'admin.error': 'An error occurred',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.back': 'Back',
    'common.success': 'Success',
    'common.deleteConfirm': 'Are you sure you want to delete this?',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.ok': 'OK',
    'common.viewMore': 'View More',
    'common.viewLess': 'View Less',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.export': 'Export',
    'common.import': 'Import',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.feed': 'التغذية',
    'nav.profile': 'الملف الشخصي',
    'nav.connections': 'الاتصالات',
    'nav.messages': 'الرسائل',
    'nav.jobs': 'الوظائف',
    'nav.events': 'الفعاليات',
    'nav.groups': 'المجموعات',
    'nav.search': 'البحث',
    'nav.admin': 'المشرف',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'ابدأ الآن',
    'nav.logout': 'تسجيل الخروج',
    'nav.companies': 'الشركات',
    'nav.users': 'المستخدمين',
    
    // Landing Page
    'landing.title': 'تواصل. تعاون. نمّ.',
    'landing.titleHighlight': 'نمّ.',
    'landing.subtitle': 'الشبكة الاجتماعية B2B الرائدة للشركات للتواصل ومشاركة الفرص وبناء شراكات دائمة.',
    'landing.cta.getStarted': 'ابدأ مجانًا',
    'landing.cta.signIn': 'تسجيل الدخول',
    'landing.stats.companies': '10K+',
    'landing.stats.companiesLabel': 'شركات',
    'landing.stats.connections': '50K+',
    'landing.stats.connectionsLabel': 'اتصالات',
    'landing.stats.events': '5K+',
    'landing.stats.eventsLabel': 'فعاليات',
    'landing.stats.industries': '100+',
    'landing.stats.industriesLabel': 'صناعات',
    'landing.features.title': 'كل ما تحتاجه للنجاح',
    'landing.features.subtitle': 'أدوات قوية مصممة للتواصل التجاري الحديث',
    'landing.features.profiles.title': 'ملفات الشركات',
    'landing.features.profiles.description': 'أنشئ ملفات شركات مفصلة تعرض عملك وخدماتك وخبراتك.',
    'landing.features.connections.title': 'الاتصالات التجارية',
    'landing.features.connections.description': 'تواصل مع الشركات الأخرى وشكل شراكات ووسع شبكتك.',
    'landing.features.jobs.title': 'وظائف',
    'landing.features.jobs.description': 'انشر وابحث عن فرص عمل داخل مجتمع B2B.',
    'landing.features.events.title': 'فعاليات',
    'landing.features.events.description': 'اكتشف واستضيف فعاليات الصناعة والندوات عبر الإنترنت وجلسات التواصل.',
    'landing.features.groups.title': 'مجموعات',
    'landing.features.groups.description': 'انضم إلى مجموعات محددة بالصناعة لمناقشة الاتجاهات ومشاركة الرؤى.',
    'landing.features.reviews.title': 'تقييمات ومراجعات',
    'landing.features.reviews.description': 'ابن الثقة مع مراجعات وتقييمات موثقة من الشركاء التجاريين.',
    'landing.testimonials.title': 'موثوق من قبل الشركات العالمية',
    'landing.testimonials.testimonial1.quote': "ساعدنا B2BNet في العثور على شركاء رائعين لم نكن لنكتشفهم بطريقة أخرى.",
    'landing.testimonials.testimonial1.author': "سارة تشين",
    'landing.testimonials.testimonial1.role': "المديرة التنفيذية، تكفنتشرز إنك.",
    'landing.testimonials.testimonial2.quote': "فرص التواصل على هذه المنصة غيرت من عملنا.",
    'landing.testimonials.testimonial2.author': "مايكل رودريغيز",
    'landing.testimonials.testimonial2.role': "المدير، حلول عالمية محدودة.",
    'landing.testimonials.testimonial3.quote': "لقد حصلنا على عقود متعددة من خلال الاتصالات التي تمت على B2BNet.",
    'landing.testimonials.testimonial3.author': "إيميلي واتسون",
    'landing.testimonials.testimonial3.role': "نائبة رئيس المبيعات، إينوفيتكورب",
    'landing.cta.title': 'هل أنت مستعد لنمو شبكتك التجارية؟',
    'landing.cta.subtitle': 'انضم إلى آلاف الشركات التي تتصل بالفعل على B2BNet',
    'landing.cta.createAccount': 'إنشاء حسابك',
    'footer.tagline': 'نربط الشركات، نبني الشراكات.',
    'footer.platform': 'المنصة',
    'footer.support': 'الدعم',
    'footer.legal': 'قانوني',
    'footer.features': 'الميزات',
    'footer.pricing': 'الأسعار',
    'footer.about': 'حول',
    'footer.helpCenter': 'مركز المساعدة',
    'footer.contact': 'اتصل بنا',
    'footer.documentation': 'التوثيق',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.security': 'الأمان',
    'footer.copyright': '© 2026 B2BNet. جميع الحقوق محفوظة. بواسطة',
    
    // Features Page
    'features.title': 'الميزات',
    'features.subtitle': 'كل ما تحتاجه للنجاح على منصتنا',
    'features.analytics': 'تحليلات متقدمة',
    'features.analyticsDesc': 'احصل على رؤى مع أدوات التحليل والتقارير التفصيلية لتتبع أدائك.',
    'features.security': 'أمان على مستوى المؤسسات',
    'features.securityDesc': 'أمان على مستوى البنوك مع تشفير من طرف إلى طرف لحماية بياناتك.',
    'features.global': 'وصول عالمي',
    'features.globalDesc': 'تواصل مع الشركات في جميع أنحاء العالم ووسع نطاق وجودك في السوق.',

    // Pricing Page
    'pricing.title': 'الأسعار',
    'pricing.subtitle': 'اختر الخطة التي تناسب احتياجات عملك',
    'pricing.free': 'مجاني',
    'pricing.pro': 'احترافي',
    'pricing.enterprise': 'مؤسسي',
    'pricing.perMonth': '/شهر',
    'pricing.basicProfile': 'ملف شركة أساسي',
    'pricing.limitedConnections': 'اتصالات محدودة (50)',
    'pricing.basicSearch': 'بحث أساسي',
    'pricing.getStarted': 'ابدأ الآن',
    'pricing.enhancedProfile': 'ملف شركة محسن',
    'pricing.unlimitedConnections': 'اتصالات غير محدودة',
    'pricing.advancedAnalytics': 'تحليلات متقدمة',
    'pricing.prioritySupport': 'دعم أولوية',
    'pricing.startTrial': 'ابدأ تجربة مجانية',
    'pricing.mostPopular': 'الأكثر شعبية',
    'pricing.custom': 'مخصص',
    'pricing.customIntegrations': 'تكاملات مخصصة',
    'pricing.dedicatedSupport': 'دعم مخصص',
    'pricing.sla': 'ضمان SLA',
    'pricing.apiAccess': 'وصول API',
    'pricing.contactSales': 'اتصل بالمبيعات',

    // About Page
    'about.title': 'من نحن',
    'about.subtitle': 'نبني مستقبل الشبكات التجارية',
    'about.mission': 'رسالتنا',
    'about.missionDesc': 'تمكين الشركات في جميع أنحاء العالم من خلال إنشاء اتصالات هادفة وفرص للنمو.',
    'about.vision': 'رؤيتنا',
    'about.visionDesc': 'شبكة عالمية حيث يمكن لكل شركة أن تزدهر وتتعاون وتنجح معًا.',
    'about.values': 'قيمنا',
    'about.trust': 'الثقة',
    'about.trustDesc': 'نبني علاقات دائمة من خلال الشفافية والنزاهة.',
    'about.innovation': 'الابتكار',
    'about.innovationDesc': 'نتطور باستمرار لتلبية احتياجات الشركات الحديثة.',
    'about.community': 'المجتمع',
    'about.communityDesc': 'نؤمن بقوة المجتمع والتعاون.',
    'about.excellence': 'التميز',
    'about.excellenceDesc': 'نسعى للتميز في كل ما نقوم به.',
    'about.team': 'فريقنا',
    'about.teamDesc': 'فريقنا المتنوع من الخبراء مكرس لجعل الشبكات التجارية B2B في متناول جميع الشركات وفعالة لها.',

    // Help Center Page
    'help.title': 'مركز المساعدة',
    'help.subtitle': 'ابحث عن إجابات للأسئلة الشائعة',
    'help.gettingStarted': 'البدء',
    'help.gettingStartedDesc': 'تعلم كيفية إنشاء حسابك وإعداد ملفك الشخصي والبدء في الشبكات.',
    'help.faq': 'الأسئلة الشائعة',
    'help.faq1.q': 'كيف يمكنني إنشاء ملف شركة؟',
    'help.faq1.a': 'بعد التسجيل، انتقل إلى لوحة التحكم وانقر على "إكمال الملف الشخصي". املأ تفاصيل شركتك واحفظها.',
    'help.faq2.q': 'كيف يمكنني الاتصال بالشركات الأخرى؟',
    'help.faq2.a': 'استخدم صفحة الاتصالات للبحث عن الشركات وإرسال طلبات الاتصال. بمجرد القبول، يمكنك البدء في التعاون.',
    'help.faq3.q': 'كيف يمكنني نشر وظيفة؟',
    'help.faq3.a': 'انتقل إلى صفحة الوظائف وانقر على "نشر وظيفة". املأ التفاصيل وانشر للوصول إلى آلاف الشركات.',
    'help.faq4.q': 'هل يمكنني استضافة فعاليات على المنصة؟',
    'help.faq4.a': 'نعم! انتقل إلى صفحة الفعاليات وانقر على "إنشاء فعالية". يمكنك استضافة فعاليات افتراضية ووجاهية.',
    'help.faq5.q': 'كيف يمكنني الإبلاغ عن محتوى غير لائق؟',
    'help.faq5.a': 'انقر على زر "الإبلاغ" في أي منشور أو ملف شخصي. سيراجع فريق الإشراف المحتوى خلال 24 ساعة.',
    'help.needMoreHelp': 'تحتاج إلى مزيد من المساعدة؟',
    'help.needMoreHelpDesc': 'فريق الدعم الخاص بنا متاح على مدار الساعة طوال أيام الأسبوع لمساعدتك في أي أسئلة أو مشاكل.',

    // Contact Page
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل مع فريقنا',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.address': 'العنوان',
    'contact.addressValue': '123 طريق الأعمال، جناح 100\nسان فرانسيسكو، كاليفورنيا 94107\nالولايات المتحدة',
    'contact.yourName': 'اسمك',
    'contact.yourEmail': 'بريدك الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.sendMessage': 'إرسال الرسالة',
    'contact.messageSent': 'تم إرسال رسالتك! سنتواصل معك قريبًا.',

    // Documentation Page
    'docs.title': 'التوثيق',
    'docs.subtitle': 'أدلة شاملة ومراجع API',
    'docs.gettingStarted': 'البدء',
    'docs.gettingStartedDesc': 'تعلم أساسيات استخدام منصتنا و API.',
    'docs.apiReference': 'مرجع API',
    'docs.apiReferenceDesc': 'توثيق API كامل مع أمثلة ونقاط النهاية.',
    'docs.guides': 'الأدلة والبرامج التعليمية',
    'docs.guidesDesc': 'برامج تعليمية خطوة بخطوة لمساعدتك في الحصول على أقصى استفادة من منصتنا.',
    'docs.support': 'الدعم',
    'docs.supportDesc': 'موارد إضافية ومعلومات الاتصال للدعم الفني.',

    // Privacy Page
    'privacy.title': 'سياسة الخصوصية',
    'privacy.subtitle': 'كيف نحمي ونستخدم بياناتك',
    'privacy.collection': 'المعلومات التي نجمعها',
    'privacy.collectionDesc': 'نجمع المعلومات التي تقدمها مباشرة، مثل تفاصيل شركتك ومعلومات ملفك الشخصي واتصالاتك. كما نجمع بيانات الاستخدام لتحسين خدماتنا.',
    'privacy.usage': 'كيف نستخدم معلوماتك',
    'privacy.usageDesc': 'نستخدم معلوماتك لتقديم وتحسين خدماتنا، وتسهيل الاتصالات، وإرسال التحديثات، والتواصل معك. لا نبيع بياناتك الشخصية أبدًا.',
    'privacy.sharing': 'مشاركة المعلومات',
    'privacy.sharingDesc': 'نشارك معلوماتك فقط بموافقتك أو كما هو ضروري لتقديم خدماتنا. هذا يشمل ربطك بالشركات الأخرى على المنصة.',
    'privacy.security': 'أمان البيانات',
    'privacy.securityDesc': 'ننفذ تدابير أمنية معيارية لحماية بياناتك، بما في ذلك التشفير وضوابط الوصول والتدقيق الأمني المنتظم.',
    'privacy.rights': 'حقوقك',
    'privacy.rightsDesc': 'لديك الحق في الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها. يمكنك أيضًا إلغاء الاشتراك في بعض أنشطة معالجة البيانات.',

    // Terms Page
    'terms.title': 'شروط الخدمة',
    'terms.subtitle': 'قواعد وإرشادات استخدام منصتنا',
    'terms.acceptance': 'قبول الشروط',
    'terms.acceptanceDesc': 'بالوصول إلى B2BNet أو استخدامه، فإنك توافق على الالتزام بهذه شروط الخدمة. إذا لم توافق، قد لا تتمكن من استخدام الخدمة.',
    'terms.use': 'استخدام الخدمة',
    'terms.useDesc': 'منصتنا للأغراض التجارية المشروعة فقط. توافق على استخدام الخدمة وفقًا لجميع القوانين واللوائح المعمول بها.',
    'terms.accounts': 'الحسابات',
    'terms.accountsDesc': 'أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك وجميع الأنشطة تحت حسابك.',
    'terms.content': 'محتوى المستخدم',
    'terms.contentDesc': 'تحتفظ بملكية المحتوى الذي تنشره، ولكن تمنحنا ترخيصًا لاستخدامه لتقديم وتحسين خدماتنا. يجب ألا ينتهك المحتوى حقوق الملكية الفكرية.',
    'terms.termination': 'الإنهاء',
    'terms.terminationDesc': 'نحتفظ بالحق في تعليق أو إنهاء الحسابات التي تنتهك هذه الشروط أو تشارك في أنشطة ضارة.',

    // Security Page
    'security.title': 'الأمان',
    'security.subtitle': 'كيف نحمي بيانات عملك',
    'security.encryption': 'التشفير من طرف إلى طرف',
    'security.encryptionDesc': 'جميع البيانات المرسلة بين متصفحك وخوادمنا مشفرة باستخدام TLS 1.3. كما نقوم بتشفير البيانات الحساسة في الراحة.',
    'security.authentication': 'مصادقة آمنة',
    'security.authenticationDesc': 'ندعم المصادقة متعددة العوامل ونستخدم خوارزميات تجزئة كلمات المرور الآمنة لحماية حسابك.',
    'security.monitoring': 'مراقبة على مدار الساعة',
    'security.monitoringDesc': 'فريق الأمان الخاص بنا يراقب الأنظمة على مدار الساعة للكشف والاستجابة للتهديدات المحتملة.',
    'security.compliance': 'الامتثال',
    'security.complianceDesc': 'نمتثل للمعايير واللوائح الصناعية بما في ذلك GDPR و CCPA و SOC 2 Type II.',
    'security.reporting': 'الإبلاغ عن الثغرات',
    'security.reportingDesc': 'نشجع الإفصاح المسؤول عن الثغرات الأمنية. اتصل بفريق الأمان لدينا للإبلاغ عن أي مشاكل.',

    // Auth Pages
    'auth.welcomeBack': 'مرحبًا بعودتك',
    'auth.signInSubtitle': 'سجل دخول إلى حساب B2B Network الخاص بك',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.emailPlaceholder': 'company@example.com',
    'auth.passwordPlaceholder': 'أدخل كلمة المرور',
    'auth.signIn': 'تسجيل الدخول',
    'auth.invalidCredentials': 'بريد إلكتروني أو كلمة مرور غير صالحة',
    'auth.or': 'أو',
    'auth.createAccount': 'إنشاء حساب جديد',
    'auth.noAccount': "ليس لديك حساب؟ ",
    'auth.registerHere': 'سجل هنا',
    'auth.joinBusinesses': 'انضم إلى آلاف الشركات على منصتنا',
    'auth.registrationFailed': 'فشل التسجيل. قد يكون البريد الإلكتروني موجودًا بالفعل.',
    'auth.companyInfo': 'معلومات الشركة',
    'auth.accountDetails': 'تفاصيل الحساب',
    'auth.companyName': 'اسم الشركة',
    'auth.companyPlaceholder': 'شركتك المحدودة',
    'auth.industry': 'الصناعة',
    'auth.selectIndustry': 'اختر الصناعة',
    'auth.description': 'الوصف',
    'auth.descriptionPlaceholder': 'وصف موجز لشركتك',
    'auth.website': 'الموقع الإلكتروني',
    'auth.websitePlaceholder': 'https://yourcompany.com',
    'auth.location': 'الموقع',
    'auth.locationPlaceholder': 'المدينة، البلد',
    'auth.companySize': 'حجم الشركة',
    'auth.selectSize': 'اختر الحجم',
    'auth.yourName': 'اسمك',
    'auth.namePlaceholder': 'جون دو',
    'auth.logoUrl': 'رابط الشعار (اختياري)',
    'auth.logoPlaceholder': 'https://example.com/logo.png',
    'auth.continueAccount': 'المتابعة إلى تفاصيل الحساب',
    'auth.back': 'رجوع',
    'auth.signInInstead': 'تسجيل الدخول بدلاً من ذلك',
    'auth.haveAccount': 'هل لديك حساب بالفعل؟ ',
    'auth.growBusiness': 'نمّي شبكتك التجارية',
    'auth.connectPartners': 'تواصل مع الشركاء والعملاء وقادة الصناعة',
    
    // Dashboard
    'dashboard.welcome': 'مرحبًا بعودتك',
    'dashboard.stats.connections': 'اتصالات',
    'dashboard.stats.posts': 'منشورات حديثة',
    'dashboard.stats.jobs': 'وظائف نشطة',
    'dashboard.stats.events': 'فعاليات قادمة',
    'dashboard.recentPosts': 'منشورات حديثة',
    'dashboard.latestJobs': 'أحدث الوظائف',
    'dashboard.upcomingEvents': 'الفعاليات القادمة',
    'dashboard.viewAllPosts': 'عرض كل المنشورات',
    'dashboard.viewAllJobs': 'عرض كل الوظائف',
    'dashboard.viewAllEvents': 'عرض كل الفعاليات',
    
    // Feed
    'feed.createPost': 'إنشاء منشور',
    'feed.postPlaceholder': 'ما الذي يحدث في عملك؟',
    'feed.postButton': 'نشر',
    'feed.companyId': 'معرف الشركة',
    
    // Profile
    'profile.verified': 'موثق',
    'profile.industry': 'الصناعة',
    'profile.location': 'الموقع',
    'profile.size': 'الحجم',
    'profile.website': 'الموقع الإلكتروني',
    'profile.description': 'الوصف',
    'profile.notSpecified': 'غير محدد',
    'profile.noDescription': 'لم يتم تقديم وصف',
    'profile.badges': 'الشارات',
    'profile.connections': 'اتصالات',
    'profile.noConnections': 'لا توجد اتصالات بعد',
    'profile.connectionId': 'معرف الاتصال',
    'profile.status': 'الحالة',
    'profile.reviews': 'تقييمات',
    'profile.noReviews': 'لا توجد تقييمات بعد',
    'profile.reviewer': 'المقيّم',
    'profile.connected': 'أنت متصل',
    'profile.requestSent': 'تم إرسال طلب الاتصال - في انتظار الرد',
    'profile.sendRequest': 'إرسال طلب اتصال',
    
    // Connections
    'connections.sendRequest': 'إرسال طلب اتصال',
    'connections.selectCompany': 'اختر شركة',
    'connections.sendRequestButton': 'إرسال الطلب',
    'connections.pendingRequests': 'الطلبات المعلقة',
    'connections.from': 'من',
    'connections.accept': 'قبول',
    'connections.reject': 'رفض',
    'connections.yourConnections': 'اتصالاتك',
    'connections.noConnections': 'لا توجد اتصالات بعد. أرسل طلبات إلى شركات أخرى لبناء شبكتك!',
    'connections.connectedWith': 'متصل مع',
    'connections.connectedOn': 'متصل في',
    'connections.remove': 'إزالة',
    'connections.requestSent': 'تم إرسال طلب الاتصال!',
    'connections.requestFailed': 'فشل في إرسال الطلب. قد يكون الطلب موجودًا بالفعل.',
    'connections.removeConfirm': 'هل أنت متأكد من أنك تريد إزالة هذا الاتصال؟',
    
    // Messages
    'messages.conversations': 'المحادثات',
    'messages.chatWith': 'محادثة مع',
    'messages.typeMessage': 'اكتب رسالة...',
    'messages.send': 'إرسال',
    'messages.selectCompany': 'اختر شركة لبدء المحادثة',
    
    // Jobs
    'jobs.postJob': 'نشر وظيفة',
    'jobs.createPosting': 'إنشاء إعلان وظيفي',
    'jobs.title': 'العنوان',
    'jobs.description': 'الوصف',
    'jobs.requirements': 'المتطلبات',
    'jobs.location': 'الموقع',
    'jobs.type': 'نوع الوظيفة',
    'jobs.salary': 'نطاق الراتب (اختياري)',
    'jobs.fullTime': 'دوام كامل',
    'jobs.partTime': 'دوام جزئي',
    'jobs.contract': 'عقد',
    'jobs.freelance': 'عمل حر',
    'jobs.deleteConfirm': 'هل أنت متأكد من أنك تريد حذف هذه الوظيفة؟',
    
    // Events
    'events.createEvent': 'إنشاء فعالية',
    'events.title': 'العنوان',
    'events.description': 'الوصف',
    'events.datetime': 'التاريخ والوقت',
    'events.location': 'الموقع',
    'events.type': 'نوع الفعالية',
    'events.networking': 'تواصل',
    'events.conference': 'مؤتمر',
    'events.webinar': 'ندوة عبر الإنترنت',
    'events.workshop': 'ورشة عمل',
    'events.meetup': 'لقاء',
    'events.virtual': 'فعالية افتراضية',
    'events.meetingLink': 'رابط الاجتماع',
    'events.deleteConfirm': 'هل أنت متأكد من أنك تريد حذف هذه الفعالية؟',
    
    // Groups
    'groups.createGroup': 'إنشاء مجموعة',
    'groups.name': 'اسم المجموعة',
    'groups.description': 'الوصف',
    'groups.industry': 'الصناعة',
    'groups.private': 'مجموعة خاصة',
    'groups.public': 'عام',
    'groups.deleteConfirm': 'هل أنت متأكد من أنك تريد حذف هذه المجموعة؟',
    
    // Search
    'search.placeholder': 'البحث عن الشركات والمنشورات والوظائف والفعاليات والمجموعات...',
    'search.all': 'الكل',
    'search.noResults': 'لم يتم العثور على نتائج',
    
    // Admin
    'admin.stats': 'إحصائيات',
    'admin.totalCompanies': 'إجمالي الشركات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalPosts': 'إجمالي المنشورات',
    'admin.totalConnections': 'إجمالي الاتصالات',
    'admin.totalJobs': 'إجمالي الوظائف',
    'admin.totalEvents': 'إجمالي الفعاليات',
    'admin.totalGroups': 'إجمالي المجموعات',
    'admin.manageCompanies': 'إدارة الشركات',
    'admin.managePosts': 'إدارة المنشورات',
    'admin.manageUsers': 'إدارة المستخدمين',
    'admin.manageEvents': 'إدارة الفعاليات',
    'admin.manageGroups': 'إدارة المجموعات',
    'admin.manageJobs': 'إدارة الوظائف',
    'admin.manageMessages': 'إدارة الرسائل',
    'admin.company': 'الشركة',
    'admin.role': 'الدور',
    'admin.userRole': 'مستخدم',
    'admin.adminRole': 'مشرف',
    'admin.deleteCompanyConfirm': 'هل أنت متأكد من أنك تريد حذف هذه الشركة؟',
    'admin.deletePostConfirm': 'هل أنت متأكد من أنك تريد حذف هذا المنشور؟',
    'admin.deleteEventConfirm': 'هل أنت متأكد من أنك تريد حذف هذه الفعالية؟',
    'admin.deleteGroupConfirm': 'هل أنت متأكد من أنك تريد حذف هذه المجموعة؟',
    'admin.deleteJobConfirm': 'هل أنت متأكد من أنك تريد حذف هذه الوظيفة؟',
    'admin.banUser': 'حظر المستخدم',
    'admin.unbanUser': 'إلغاء حظر المستخدم',
    'admin.banCompany': 'حظر الشركة',
    'admin.unbanCompany': 'إلغاء حظر الشركة',
    'admin.banConfirm': 'هل أنت متأكد من أنك تريد حظر هذا {type}؟ سيتم منعهم من الوصول إلى المنصة.',
    'admin.unbanConfirm': 'هل أنت متأكد من أنك تريد إلغاء حظر هذا {type}؟',
    'admin.edit': 'تعديل',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.search': 'بحث',
    'admin.filter': 'تصفية',
    'admin.bulkActions': 'إجراءات جماعية',
    'admin.selectAll': 'تحديد الكل',
    'admin.deleteSelected': 'حذف المحدد',
    'admin.banSelected': 'حظر المحدد',
    'admin.settings': 'إعدادات النظام',
    'admin.siteSettings': 'إعدادات الموقع',
    'admin.maintenanceMode': 'وضع الصيانة',
    'admin.enableMaintenance': 'تفعيل وضع الصيانة',
    'admin.disableMaintenance': 'تعطيل وضع الصيانة',
    'admin.maintenanceWarning': 'الموقع حاليًا في وضع الصيانة. فقط المشرفون يمكنهم الوصول.',
    'admin.registrationOpen': 'التسجيل مفتوح',
    'admin.toggleRegistration': 'تبديل التسجيل',
    'admin.registrationOpenDesc': 'السماح للمستخدمين الجدد بالتسجيل',
    'admin.registrationClosed': 'التسجيل مغلق',
    'admin.analytics': 'التحليلات',
    'admin.systemLogs': 'سجلات النظام',
    'admin.viewLogs': 'عرض السجلات',
    'admin.clearLogs': 'مسح السجلات',
    'admin.exportData': 'تصدير البيانات',
    'admin.importData': 'استيراد البيانات',
    'admin.backup': 'نسخة احتياطية',
    'admin.restore': 'استعادة',
    'admin.createBackup': 'إنشاء نسخة احتياطية',
    'admin.restoreBackup': 'استعادة من نسخة احتياطية',
    'admin.noItems': 'لم يتم العثور على عناصر',
    'admin.addNew': 'إضافة جديد',
    'admin.view': 'عرض',
    'admin.createdAt': 'تاريخ الإنشاء',
    'admin.updatedAt': 'تاريخ التحديث',
    'admin.status': 'الحالة',
    'admin.active': 'نشط',
    'admin.inactive': 'غير نشط',
    'admin.banned': 'محظور',
    'admin.pending': 'معلق',
    'admin.approved': 'موافق عليه',
    'admin.rejected': 'مرفوض',
    'admin.all': 'الكل',
    'admin.confirmAction': 'تأكيد الإجراء',
    'admin.actionSuccess': 'تم إكمال الإجراء بنجاح',
    'admin.actionFailed': 'فشل الإجراء. يرجى المحاولة مرة أخرى.',
    'admin.loading': 'جاري التحميل...',
    'admin.error': 'حدث خطأ',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.back': 'رجوع',
    'common.success': 'نجاح',
    'common.deleteConfirm': 'هل أنت متأكد من أنك تريد حذف هذا؟',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.ok': 'موافق',
    'common.viewMore': 'عرض المزيد',
    'common.viewLess': 'عرض أقل',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.apply': 'تطبيق',
    'common.download': 'تنزيل',
    'common.upload': 'رفع',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [direction, setDirection] = useState('ltr');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
    setDirection(prev => prev === 'ltr' ? 'rtl' : 'ltr');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
